first dockerfile completed

diff --git a/tests/docker/EL6 b/tests/docker/EL6
--- a/tests/docker/EL6
+++ b/tests/docker/EL6
@@ -44,8 +44,40 @@ RUN java -version 2>&1 \
     | grep "$JAVA" \
     && (echo 'Functional test passed' && exit 0) \
     || (echo 'Functional test failed' && exit 1)
-# JAVA_HOME variable check
-RUN echo $JAVA_HOME \
+
+# Set new JAVA Version
+ENV JAVA_MINOR 101
+ENV JAVA "1.$JAVA_MAJOR.0_$JAVA_MINOR"
+
+# Run the playbook
+RUN ansible-playbook test.yml -i test.ini --connection=local --sudo
+# Idempotency check
+RUN ansible-playbook test.yml -i test.ini --connection=local --sudo \
+    | grep -q 'changed=0.*failed=0' \
+    && (echo 'Idempotence test: pass' && exit 0) \
+    || (echo 'Idempotence test: fail' && exit 1)
+
+# Java version check
+RUN java -version 2>&1 \
+    | grep "$JAVA" \
+    && (echo 'Functional test passed' && exit 0) \
+    || (echo 'Functional test failed' && exit 1)
+
+# Set new JAVA Version
+ENV JAVA_MAJOR 7
+ENV JAVA_MINOR 79
+ENV JAVA "1.$JAVA_MAJOR.0_$JAVA_MINOR"
+
+# Run the playbook
+RUN ansible-playbook test.yml -i test.ini --connection=local --sudo
+# Idempotency check
+RUN ansible-playbook test.yml -i test.ini --connection=local --sudo \
+    | grep -q 'changed=0.*failed=0' \
+    && (echo 'Idempotence test: pass' && exit 0) \
+    || (echo 'Idempotence test: fail' && exit 1)
+
+# Java version check
+RUN java -version 2>&1 \
     | grep "$JAVA" \
     && (echo 'Functional test passed' && exit 0) \
     || (echo 'Functional test failed' && exit 1)
